### ISSUE TITLE
cannot find the .exe file

### ISSUE THREAD

**Issue by cellerich** [hawkeye-stan/msfs-touch-panel#1]
Hi Stan

**First, thanks for your contribution to the MSFS community.**

I'm interested in the "Experimental Feature 2", displaying the FMC, PFD and MFD of the CJ4 on another device.
However, I'm not able to find the .exe file. 
Do I need to get Visual Studio and compile it myself?

**Comment by hawkeye-stan** [comment]
Hi Cello Spring,

I've just created the first release of the app, you can go to release section to download the zip file. The compiled exe will be there. Documentation and code has been updated from changes I did the past few days. Please follow Experimental Feature #2 documentation for installation instruction.

https://github.com/hawkeye-stan/msfs-touch-panel/blob/master/ExperimentalFeature2.md

Also, I've updated the app to use MobiFlight Connector instead of just FSUIPC WASM, please also follow the main app installation instruction to copy the MobiFlight WASM into your community folder.

Experimental feature is very "experimental" and I haven't flew extensively with the HTML render panel for CJ4 since I mostly flew the G1000NXi. Please report back if you run into any issue with the CJ4.

For CJ4 panel, I believe anything that deal with Bing Map data or real-time HTML Canvas draw data will not work. Unfortunately, I still haven't figured out a solution for them yet.

**Comment by cellerich** [comment]
Hi Stan

Thanks very much!
I will try it out today.

My main goal is to get the MCDU/FMC screen out as a html page and then build an App or Web version of the FMC to control it from an iPad or Tablet. The popout screens are a big FPS hit for everybody.
Something like the FlyByWire team did for the A320 MCDU.

I keep you posted should I find other ways for the Bing Map issue.

**Comment by hawkeye-stan** [comment]
That's awesome! When I started the experimental part of this project, I've the same goal of removing the pop out performance penalty and also getting a touchable bezel interface for G1000NXi first, then when I flew FBW A32X, the MCDU. And then FBW came out with their MCDU server few weeks back which directly ties to their JavaScript code of their plane module! 

The performance penalty is still there, but it is definitely much smaller since the performance limitation is how fast your CPU can parses CoherentGT websocket messages, renders the HTML DOM and support number of concurrent connections (one for each panel),

You can fork the repo and check out the code within the project for FlyByWire A32X MCDU or the G1000NXi bezel. The web button pages are coded in ReactJs.  There are 3 files that control how to add a new "buttonpanel" to your CJ4 FMC.

In touchpanelhost/data
- PlanePanelProfileInfo.json  (add a new one for CJ4 as type "buttonpanel", you can follow the sample for FBW CDU parameters)

The rendered HTML MCDU will be a iframe page inside the button panel HTML page.

In reactclient\src\Services\DataProviders
- PopoutPanelDefinition.js  (This defines the clickable buttons location in the html, use FBWA32NX_CDU_DEF as sample)
- PopoutPanelStyles.js (just add a new one similar to FBWA32NX_CDU_STYLES, adjust height, width, and aspect ratio)

The above two files will eventually become json once I get around refactoring the code.

Also in folder reactclient/public/img/fbwa32nx, you will find graphical assets I created for FBW MCDU and photoshop files. CJ4 FMS is similar and you can reuse the FBW ones or add new ones. Clone the folder, each plane needs it individual one.

Hope this helps and have fun coding!!!
Stanley

**Comment by cellerich** [comment]
Thanks Stan for the pointers!
Will report back once I have some success ;-)
