### ISSUE TITLE
PFD - G1000 (experimental 2) not working on Ipad/Iphone

### ISSUE THREAD

**Issue by kromosomX** [hawkeye-stan/msfs-touch-panel#5]
I can't get PFD (G1000 -C172) to work from my Ipad or Iphone.  Overlay is displayed but bottom parts of all the rotary knobs are missing. Also it never goes past "Conecting ...."  Touch panel works from Ipad or Iphone

If  I connect  from  a local browser  everything works fine.

**Comment by hawkeye-stan** [comment]
I'm not able to reproduce your issue on both ipad pro (iOS 15.2.1), android tablet and android phone.

The problem is weird.  For you to be able to see the bezel on ipad means your ipad is definitely connecting to touch panel server. But missing buttons, rotary knobs images and possibly react JavaScript's mean somehow these assets are not coming across to your ipad.

Would you be able to try to clear ipad browser cache? Also try the different menu options for the PFD and see if anyone of them work?

PFD => this will only show the panel rendered screen

PFD (button overlay only) => this will only show the bezel. When touching any of the knob, a semi-transparent knob control should pop up. Not very useful for the browser but more for test only.

PFD (with button overlay) => this will show both, bezel and rendered screen

**Comment by hawkeye-stan** [comment]
Here is an image of what the semi-transparent rotary knob would look like on ipad

![pfd-ipad](https://user-images.githubusercontent.com/72271266/151453781-b9918b20-2b97-45a6-8a46-f887401231ce.jpg)
d

**Comment by kromosomX** [comment]
![2022-01-27_23-30-29](https://user-images.githubusercontent.com/19895037/151454400-4ad75369-cfc5-440c-a1d8-da4d14199695.jpg)
This is how it looks on my end. Strange thing is that if i slide my finger anywhere (inside or on the bezel) i can scroll the whole think up and down like a web page.


Hmm.... it may have something to do with the fact that I am on IOS 14.3... I tried connecting from my Android TV and the same thing happens. I will try conecting from another Windows computer tomorrow and I'll report back. 

Oh.. and no version works - with or without overlay. Even the overlay by itself is missing parts of knobs.

**Comment by hawkeye-stan** [comment]
Thanks for the screenshot. The page rendering definitely does not look right. Something is off with the code. I'll investigate on my end also.

**Comment by kromosomX** [comment]
I already tried in Chrome on iOS. Same problem. I'll try few ideas tomorrow evening... I'm done for the night...

**Comment by hawkeye-stan** [comment]
With limited usage of browsestack.com (1 min trial usage per OS, LOL!), I was able to reproduce your screenshot above of incorrect rendering of web panel. I believe the cause is extensive usage of CSS aspect-ratio in my app which most modern browser support except pre-iOS 15 Safari. Also all variants of browser installed on iOS (chrome, firefox, etc) still use the same webkit rendering engine iOS provided.

Please try version 1.0.1 hotfix1 package in the release section. You can overwrite the content in existing installed folder. I hope this works on your iPad iOS 14.3.

**Comment by kromosomX** [comment]
Wow. Talk about efficient usage of time. Impressive. I did a quick test and now the buttton overlay is working. If I choose PFD (with button overlay) the overlay is working, but the PFD is not. I get Connecting.... forever. Same thing if I choose PFD.

I think this is some networking issue on my part, because same thing happens if i try to connect from another Windows machine. Does the client connect to the debugger directly? I should probabbly open some port on the firewall manually...

I’ll investigate after I get home from work.

Anyway, thank you for all your effort.

**Comment by kromosomX** [comment]
It is working now... I had to open port 19999 so debugger can be reached from the network.

Thank you.

**Comment by hawkeye-stan** [comment]
That's awesome! Have fun with the experimental part of this project using coherent debugger info to replicate the panel screen.

But this project (debugger web panel part)  may become obsolete once Asobo fixes the major FPS penalty I have when popping out panels. I currently have about 15 to 20 FPS penalty and it makes it unflyable in New York City area when my FPS dips into the mid to low 20s with my mid-range computer. Really hope Asobo fixes the issue. I dived into the FPS penalty issue, kind of figure out where the problem was but wasn't able to fix it since it is their DX11 internal code that is causing the problem.

Anyway, once the FPS penalty is fixed, I will be concentrating on my other github project (Pop out panel manager) which is more popular and will continue to expand its functionalities.
